# Generated by Django 4.2.7 on 2023-12-04 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0002_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="publishers",
            field=models.ManyToManyField(
                related_name="published_topics", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
