# Generated by Django 4.2.7 on 2023-12-04 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0003_alter_newspaper_publishers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="publishers",
            field=models.ManyToManyField(
                related_name="published_newspapers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
