# Generated by Django 4.2.7 on 2023-12-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0004_alter_newspaper_publishers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
