# Generated by Django 4.2.7 on 2024-01-08 18:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0005_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["-published_date"]},
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
