# Generated by Django 4.2.7 on 2024-01-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0006_alter_newspaper_options_alter_newspaper_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="news_images",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
