# Generated by Django 4.2.7 on 2024-01-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0007_newspaper_news_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={"ordering": ["first_name"]},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="news_images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news_images/",
                verbose_name="Header Image (800x450)",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "post_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="agency_system.newspaper",
                    ),
                ),
            ],
        ),
    ]
