# Generated by Django 4.2.7 on 2024-01-16 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0008_alter_redactor_options_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
    ]
