# Generated by Django 4.2.7 on 2024-01-17 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0009_remove_comment_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-date_added"]},
        ),
    ]
