# Generated by Django 4.2.7 on 2024-01-17 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0010_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
