# Generated by Django 4.2.7 on 2024-01-17 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0012_replycomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="replycomment",
            old_name="reply_comment",
            new_name="comment_author",
        ),
    ]
