# Generated by Django 4.2.7 on 2024-01-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0013_rename_reply_comment_replycomment_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="redactor",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
