# Generated by Django 4.2.7 on 2024-01-31 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0014_redactor_bio_redactor_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="redactor",
            old_name="profile_image",
            new_name="profile_images",
        ),
    ]
