# Generated by Django 4.2.7 on 2024-02-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency_system", "0015_rename_profile_image_redactor_profile_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="replycomment",
            options={"ordering": ["-reply_date"]},
        ),
        migrations.AlterField(
            model_name="redactor",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="profile_images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="Profile Image (600x400)",
            ),
        ),
    ]
