# Generated by Django 4.2.7 on 2024-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "agency_system",
            "0016_alter_replycomment_options_alter_redactor_bio_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspaper",
            name="topic",
        ),
        migrations.AddField(
            model_name="newspaper",
            name="topic",
            field=models.ManyToManyField(
                related_name="newspapers",
                to="agency_system.topic",
                verbose_name="Select topic/topics",
            ),
        ),
    ]
